#pragma once

#define MASTER_LEFT

#ifdef RGBLIGHT_ENABLE
    #define RGB_DI_PIN D3
    #define RGBLED_NUM 14
    #define RGBLED_SPLIT { 7, 7 }
    #define RGBLIGHT_ANIMATIONS
    #define RGBLIGHT_HUE_STEP 8
    #define RGBLIGHT_SAT_STEP 8
    #define RGBLIGHT_VAL_STEP 8
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
    #define RGBLIGHT_SLEEP
    #define RGBLIGHT_LAYERS
#endif
