
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no

SPLIT_KEYBOARD = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes

LTO_ENABLE = yes

SRC += oled.c encoder.c

RGBLIGHT_ENABLE = yes